name: Build (#| TMPL_VAR name |#)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: 40ants/setup-lisp@v1
        with:
          asdf-system: (#| TMPL_VAR name |#)

      - name: Build executable
        run: ros run -- --eval "(asdf:make :scenic)"

      - uses: actions/upload-artifact@v2
        with:
          name: (#| TMPL_VAR name |#)-linux
          path: bin/

