name: Windows & Linux Build (#| TMPL_VAR name |#)
on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.github/workflows/static.yml'
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2019 ]
    runs-on: ${{ matrix.os }}
    env:
      SBCL_VERSION: 2.1.9
      VCPKG_MAX_CONCURRENCY: 1
      VCPKG_CONCURRENCY: 1
      VCPKG_DEFAULT_TRIPLET: x64-windows
      VCPKG_FEATURE_FLAGS: fastbuild,versions
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # to fetch tags

      - name: apt-get
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y sbcl wget
      - name: choco
        if: runner.os == 'Windows'
        run: choco install lessmsi make 7zip wget

      - name: mkdir cache dirs
        run: |
          mkdir -pv ~/Downloads
          mkdir -pv ~/sbcl
          mkdir -pv ~/quicklisp
          mkdir -pv ~/.cache/common-lisp
          mkdir -p ~/AppData/Local/cache/common-lisp
        shell: bash

      - name: Get Current Month
        id: current-month
        run: echo "::set-output name=value::$(date -u '+%Y-%m')"
      - name: Cache SBCL Setup
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: "cache-sbcl-${{ env.SBCL_VERSION }}-(#| TMPL_VAR name |#)"
        with:
          path: |
            ~/Downloads/
            ~/quicklisp
            ~/sbcl
            ~/.cache/common-lisp/
            ~/AppData/Local/cache/common-lisp
          key: "${{ steps.current-month.outputs.value }}-${{ env.cache-name }}-${{ matrix.os }}"
      - name: Restore Path To Cached Files
        run: |
          echo $HOME/sbcl/bin >> $GITHUB_PATH
        if: steps.cache.outputs.cache-hit == 'true'

      # - name: Write vcpkg.json
      #   if: runner.os == 'Windows'
      #   uses: DamianReeves/write-file-action
      #   with:
      #     path: vcpkg.json
      #     contents: |
      #       {
      #           "name": "example",
      #           "version-string": "0.0.1",
      #           "builtin-baseline": "5b1214315250939257ef5d62ecdcbca18cf4fb1c",
      #           "dependencies": [
      #               "zlib",
      #           ]
      #       }
      # - uses: lukka/run-vcpkg@v11
      #   if: runner.os == 'Windows'
      #   with:
      #     runVcpkgFormatString: '[`install`, `--recurse`, `--x-install-root`, `$[env.VCPKG_INSTALLED_DIR]`, `--triplet`, `$[env.VCPKG_DEFAULT_TRIPLET]`]'
      #     vcpkgGitCommitId: 5b1214315250939257ef5d62ecdcbca18cf4fb1c
      #     runVcpkgInstall: true
      # - run: cp -v vcpkg/packages/*/bin/*.dll C:/windows/system32/
      #   if: runner.os == 'Windows'

      - name: Download SBCL ${{ env.SBCL_VERSION }}
        run: |
          cd ~/Downloads
          wget http://downloads.sourceforge.net/project/sbcl/sbcl/${{ env.SBCL_VERSION }}/sbcl-${{ env.SBCL_VERSION }}-source.tar.bz2
          tar xjf sbcl-${{ env.SBCL_VERSION }}-source.tar.bz2
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Install SBCL ${{ env.SBCL_VERSION }} # linkable-runtime needed for "standalone" build
        run: |
          cd ~/Downloads/sbcl-${{ env.SBCL_VERSION }}
          sh make.sh --fancy --with-sb-linkable-runtime
          unset SBCL_HOME
          INSTALL_ROOT=~/sbcl ./install.sh
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Install quicklisp
        run: |
          export SBCL_HOME="$HOME/sbcl/lib/sbcl"
          export PATH="$HOME/sbcl/bin:${PATH}"
          cd ~/Downloads
          wget https://beta.quicklisp.org/quicklisp.lisp
          sbcl --non-interactive \
               --eval '(load "quicklisp.lisp")' \
               --eval '(quicklisp-quickstart:install)' \
               --eval '(ql-util:without-prompting (ql:add-to-init-file))' \
               --eval '(ql:update-all-dists)'
        shell: bash
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build Binary # appimage won't work on Windows
        run: |
          export PATH="$HOME/sbcl/bin:${PATH}"
          cd bin/
          make simple     SBCL_BIN="$HOME/sbcl/bin/sbcl"
          make standalone SBCL_BIN="$HOME/sbcl/bin/sbcl" SBCL_HOME="$HOME/sbcl/lib/sbcl"
          make deploy     SBCL_BIN="$HOME/sbcl/bin/sbcl"
          mv deploy (#| TMPL_VAR name |#)-${{ matrix.os }}

      - uses: vimtor/action-zip@v1
        with:
          files: bin/deploy
          dest: (#| TMPL_VAR name |#)-${{ matrix.os }}.zip

      - name: Dev Release
        uses: marvinpinto/action-automatic-releases@latest
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development ${{ matrix.os }} Build"
          files: |
            (#| TMPL_VAR name |#)-${{ matrix.os }}.zip
            bin/(#| TMPL_VAR name |#)
            bin/standalone/(#| TMPL_VAR name |#)
            LICENSE

      - name: Stable Release
        uses: marvinpinto/action-automatic-releases@latest
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          prerelease: false
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            (#| TMPL_VAR name |#)-${{ matrix.os }}.zip
            bin/(#| TMPL_VAR name |#)
            bin/standalone/(#| TMPL_VAR name |#)
            LICENSE

      - name: DEBUG SHELL
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
