name: Linux Build (#| TMPL_VAR name |#)
on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.org'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get install -y sbcl wget
      - name: Setup
        run: |
          mkdir -pv ~/Downloads
          mkdir -pv ~/quicklisp
          mkdir -pv ~/.cache/common-lisp
        shell: bash

      - name: Get Current Month
        id: current-month
        run: echo "::set-output name=value::$(date -u '+%Y-%m')"
      - name: Cache SBCL Setup
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: cache-sbcl-2.1.9-(#| TMPL_VAR name |#)
        with:
          path: |
            ~/Downloads/
            ~/quicklisp
            ~/.cache/common-lisp/
          key: "${{ steps.current-month.outputs.value }}-${{ env.cache-name }}-${{ runner.os }}"

      - name: Install quicklisp
        run: |
          cd ~/Downloads
          wget https://beta.quicklisp.org/quicklisp.lisp
          sbcl --non-interactive \
               --eval '(load "quicklisp.lisp")' \
               --eval '(quicklisp-quickstart:install)' \
               --eval '(ql-util:without-prompting (ql:add-to-init-file))' \
               --eval '(ql:update-all-dists)'
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build Binary
        run: |
          cd bin/
          make simple

      - uses: actions/upload-artifact@v2
        with:
          name: (#| TMPL_VAR name |#)-linux-x86_64
          path: bin/(#| TMPL_VAR name |#)
          if-no-files-found: error

      - name: DEBUG SHELL
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
