name: Build (#| TMPL_VAR name |#)

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:

  build:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: 40ants/setup-lisp@v2
        with:
          asdf-system: (#| TMPL_VAR name |#)
