name: Linux Default Build (#| TMPL_VAR name |#)
on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.org'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get install -y sbcl
      - name: Setup
        run: |
          mkdir -pv ~/Downloads
          mkdir -pv ~/quicklisp
          mkdir -pv ~/.cache/common-lisp
        shell: bash

      - name: Get Current Month
        id: current-month
        run: echo "::set-output name=value::$(date -u '+%Y-%m')"
      - name: Cache SBCL Setup
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: cache-sbcl-default-(#| TMPL_VAR name |#)
        with:
          path: |
            ~/Downloads/
            ~/quicklisp
            ~/.cache/common-lisp/
          key: "${{ steps.current-month.outputs.value }}-${{ env.cache-name }}-${{ runner.os }}"

      - name: Install quicklisp
        run: |
          cd ~/Downloads
          export PATH="$HOME/sbcl/bin:${PATH}"
          wget https://beta.quicklisp.org/quicklisp.lisp
          sbcl --non-interactive \
               --eval '(load "quicklisp.lisp")' \
               --eval '(quicklisp-quickstart:install)' \
               --eval '(ql-util:without-prompting (ql:add-to-init-file))' \
               --eval '(ql:update-all-dists)'
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build Binary
        run: |
          cd bin/
          make simple
          make deploy

      - name: Dev Release
        uses: marvinpinto/action-automatic-releases@latest
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            bin/(#| TMPL_VAR name |#)
            bin/deploy
            *.so
            LICENSE

      - name: Stable Release
        uses: marvinpinto/action-automatic-releases@latest
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          prerelease: false
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            bin/(#| TMPL_VAR name |#)
            bin/deploy
            *.so
            LICENSE

      - name: DEBUG SHELL
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
