name: Build (#| TMPL_VAR name |#)

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.org'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 40ants/setup-lisp@v1
        with:
          asdf-system: (#| TMPL_VAR name |#)
      - name: run tests
        run: |
          ros -e "(ql:quickload :(#| TMPL_VAR name |#)/test)" \
              -e "(ql:quickload :parachute)" \
              -e "(when (eq :FAILED (parachute:status (parachute:test '(#| TMPL_VAR name |#)-test))) (error 'testfailed))"
