name: Build (#| TMPL_VAR name |#)

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.org'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: clfoundation/sbcl:2.1.11
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-alpine
        with:
          path: |
            ~/quicklisp/
            ~/.cache/common-lisp/
          key: "${{ env.cache-name }}-${{ github.sha }}"
          restore-keys: "${{ env.cache-name }}"
      - uses: andstor/file-existence-action@v1
        id: check_files
        with:
          files: "/github/home/quicklisp/setup.lisp"
      - run: /usr/local/bin/install-quicklisp
        if: steps.check_files.outputs.files_exists != 'true'

      - name: Run tests
        run: |
          sbcl --non-interactive --no-sysinit --no-userinit \
               --load ~/quicklisp/setup.lisp \
               --load (#| TMPL_VAR name |#).asd \
               --eval "(ql:quickload :(#| TMPL_VAR name |#)/test)" \
               --eval "(parachute:test-toplevel '(#| TMPL_VAR name |#)-test)"
