name: Build and test (#| TMPL_VAR name |#)

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.org'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: APT deps
        run: |
          sudo apt-get update
          sudo apt-get install -y sbcl

      - name: Get Current Month
        id: current-month
        run: echo "::set-output name=value::$(date -u '+%Y-%m')"
      - name: mkdir cache dirs
        run: mkdir -pv ~/Downloads ~/quicklisp ~/.cache/common-lisp
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-sbcl-ubuntu
        with:
          path: |
            ~/Downloads/
            ~/quicklisp
            ~/.cache/common-lisp/
          key: "${{ steps.current-month.outputs.value }}-${{ env.cache-name }}"

      - name: Install quicklisp
        run: |
          cd ~/Downloads
          wget https://beta.quicklisp.org/quicklisp.lisp
          sbcl --non-interactive \
               --eval '(load "quicklisp.lisp")' \
               --eval '(quicklisp-quickstart:install)' \
               --eval '(ql-util:without-prompting (ql:add-to-init-file))' \
               --eval '(ql:update-all-dists)'
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run tests
        run: |
          sbcl --non-interactive --no-sysinit --no-userinit \
               --load ~/quicklisp/setup.lisp \
               --load (#| TMPL_VAR name |#).asd \
               --eval "(ql:quickload :(#| TMPL_VAR name |#)/test)" \
               --eval "(parachute:test-toplevel '(#| TMPL_VAR name |#)-test)"
